version: "3"
services:
  app:
    cpus: 2
    mem_limit: 4g
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    extra_hosts:
      - fakeservices.datajoint.io:127.0.0.1
    privileged: true # only because of dind
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined