version: "3"
services:
  app:
    cpus: 4
    mem_limit: 8g
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    extra_hosts:
      - fakeservices.datajoint.io:127.0.0.1
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined